config/routes.rb
Rails.application.routes.draw do
  post 'support/request_support'

  resources :posts do
    collection do
      get "by_tag/:tag", to: "posts#by_tag", as: "tagged"
    end
  end

  resources :idea_posts do
    collection do
      get "by_tag/:tag", to: "idea_posts#by_tag", as: "tagged"
    end
  end

  resources :tutorial_posts do
    collection do
      get "by_tag/:tag", to: "tutorial_posts#by_tag", as: "tagged"
    end
  end
  
  resources :comments, only: [:create]

  namespace :api do
    namespace :v1 do
      resources :comments
      resources :posts

      devise_scope :user do
        post "sign_up", to: "registrations#create"
        post "sign_in", to: "sessions#create"
        post "sign_out", to: "sessions#destroy"
      end
    end
  end


  namespace :admin do
    resources :idea_posts do
      collection do
        get "by_tag/:tag", to: "idea_posts#by_tag", as: "tagged"
      end
    end

    resources :tutorial_posts do
      collection do
        get "by_tag/:tag", to: "tutorial_posts#by_tag", as: "tagged"
      end
    end

    resources :posts do
      
      resources :comments

      collection do
        get "by_tag/:tag", to: "posts#by_tag", as: "tagged"
      end
      
    end

    resources :comments
    resources :subscriptions

    root to: "admin/posts#index"
  end

  resources :subscriptions, only: [:create, :show]

  devise_for :users


  get 'welcome/index'
  get 'welcome/about'
  get 'welcome/support'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "welcome#index"
end

app/models/tutorial_post.rb
class TutorialPost < Post
end

app/controllers/admin/tutorial_posts_controller.rb
class Admin::TutorialPostsController < Admin::ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.where("type = 'TutorialPost'")

    # Meta
    @title = "LÒÒCHOK | Туториалы"
    # end
  end

  def by_tag
    @posts = TutorialPost.tagged_with(params[:tag])
    render :index

    # Meta
    @title = "LÒÒCHOK | Фильтры"
    # end
  end

  # GET /posts/1 or /posts/1.json
  def show
    @recom_post1 = Post.find_by(id: "22")
    @recom_post2 = Post.find_by(id: "24")
    @recom_post3 = Post.find_by(id: "23")
  end

  # GET /posts/new
  def new
    @post = TutorialPost.new

    # Meta
    @title = "LÒÒCHOK | Новый туториал"
    # end
  end

  # GET /posts/1/edit
  def edit
    # Meta
    @title = "LÒÒCHOK | Редактирование туториала"
    # end
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(tutorial_post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to admin_tutorial_post_url(@post), notice: "Пост успешно создан" }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(tutorial_post_params)
        format.html { redirect_to admin_tutorial_post_url(@post), notice: "Пост успешно изменён" }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to admin_tutorial_posts_url, notice: "Пост успешно удалён" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tutorial_post_params
      params.require(:tutorial_post).permit(:title, :type, :description, :post_image, :tag_list, :category_id).merge(user_id: current_user.id)
    end
end
  

app/controllers/tutorial_posts_controller.rb
class TutorialPostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.where("type = 'TutorialPost'")
  end

  def by_tag
    @posts = TutorialPost.tagged_with(params[:tag])
    render :index
  end

  # GET /posts/1 or /posts/1.json
  def show
    @recom_post1 = Post.find_by(id: "22")
    @recom_post2 = Post.find_by(id: "24")
    @recom_post3 = Post.find_by(id: "23")
  end

  # GET /posts/new
  def new
    @post = TutorialPost.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(tutorial_post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to tutorial_post_url(@post), notice: "Пост успешно создан" }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(tutorial_post_params)
        format.html { redirect_to tutorial_post_url(@post), notice: "Пост успешно изменён" }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to tutorial_posts_url, notice: "Пост успешно удалён" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tutorial_post_params
      params.require(:tutorial_post).permit(:title, :type, :description, :post_image, :tag_list, :category_id).merge(user_id: current_user.id)
    end
end
  

app/views/admin/tutorial_posts/_form.html.erb
<%= form_with(model: [:admin, tutorial_post]) do |form| %>
  <% if tutorial_post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(tutorial_post.errors.count, "error") %>. Пост не может быть сохранён:</h2>

      <ul>
        <% tutorial_post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="IdeaFormPage Gride">

  <div class="LeftContent">
    <div class="BlockContent Img">
      <%= form.label :"Загрузить изображение", class:"TitleNewContent Img" %>
      <%= form.file_field :post_image, class:"FieldImg" %>
    </div>

    <!--- <div class="WrapperFakeImg">
      <div class="FieldImg Fake"></div>
      <div class="FieldImg Fake"></div>
      <div class="FieldImg Fake"></div>
    </div> --->
  </div>

  <div class="RightContent">
  <div class="TopContent">

    <div class="BlockContent Title">
      <%= form.label :"Название проекта", class:"TitleNewContent" %>
      <%= form.text_field :title, placeholder:"Кастом", class:"FieldContent Title" %>
    </div>

    <div class="BlockContent Tags">
      <%= form.label :"Тэги", class:"TitleNewContent" %>
      <%= form.text_field :tag_list, value: tutorial_post.tag_list.join(", "), class:"FieldContent Tags"  %>
    </div>
    </div>

    <div class="BottomContent">
    <div class="BlockContent Description">
      <%= form.label :"Описание проекта", class:"TitleNewContent" %>
      <%= form.text_area :description, placeholder:"Расскажите про ваш кастом", class:"FieldContent Description" %>
    </div>

    <!--- <div>
      <%#= form.label :"Добавить ссылку", style: "display: block" %>
      <%#= form.text_field :content_link %>
    </div> --->

    <div>
      <div>
        <%= form.label :"Категория" %>
        <%= form.select :category_id, options_for_select(Category.all.map { |category| [category.name, category.id]})%>
      </div>

      <div>
        <%= form.label :"Тип" %>
        <%= form.select :type, [["Пост-идея", "IdeaPost"], ["Туториал", "TutorialPost"]] %>
        <%#= form.select :type, ["IdeaPost", "TutorialPost"]%>
      </div>
    </div>

    <div class="FormButtons">
    <%= form.submit :"Опубликовать", class:"FormButton Post" %>

    <div class="FormButton Back">
      <%= link_to "Отменить", :back %>
    </div>
    </div>
  </div>
  </div>
  </div>
<% end %>

app/views/admin/tutorial_posts/_tutorial_post_page.erb
<div class="TutorialPostPageContent">

    <div class="PostPageAbout Tutorial">
        <div class="PostPageTagsRow">
            <% post.tag_list.each do |tag| %>
                <%= link_to tagged_admin_tutorial_posts_path(tag), class:"PostPageTagChip" do %>
                    <%= tag %>
                <% end %>
            <% end %>
        </div>

        <p class="PostPageDate">
            <%#= post.created_at %>
            сегодня в&nbsp;10:05
        </p>

        <div class="IdeaPostPageInfoUser">
            <div class="IdeaPostPageInfoUserAvatar"></div>
                <div class="IdeaPostPageInfoUserNames">
                <p class="IdeaPostPageInfoUserName UN"><%= post.user.email.split("@")[0] %></p>
                <p class="IdeaPostPageInfoUserName NN">@<%= post.user.email.split("@")[0] %></p>
            </div>
        </div>
    </div>

    <div class="TutorialPostPageTitleDescription">
        <h3 class="TutorialPostPageTitle"><%= post.title%></h3>
        <p class="TutorialPostPageDescription"><%= post.description %></p>
    </div>

    <div class="TutorialPostPageImg">
        <%= image_tag post.post_image.url %>
    </div>
    
    <!--- --->

    <div class="TutorialPostPageTexts">
        <h4 class="TutorialPostPageSubtitle">Подготовка материалов</h4>
        <p class="TutorialPostPageText">
        Снимите все украшения с кед и расшнуруйте их. Расшнуруйте обувь, если на ваших кедах есть шнурки. Краска обычно плохо держится на шнурках, поэтому любое окрашивание впоследствии приведет к ее отслоению.
        Если кеды сделаны из мягкой ткани, перед окрашиванием набейте их бумагой, чтобы сохранить форму. Вы рискуете испортить рисунок, если выбранные вами кеды быстро теряют форму. 
        Приклейте малярный скотч к подошве обуви, чтобы защитить ее от краски. Пятна краски через некоторое время начнут отслаиваться, и вам будет неловко носить такую обувь. Как вариант, для этой цели можно использовать маскировочную ленту.</p>
    </div>

    <div class="TutorialPostPageImg">
        <img src="/fake_content/image_13.jpg" alt="кастом" />
    </div>

    <div class="TutorialPostPageTexts">
        <h4 class="TutorialPostPageSubtitle">Техника росписи</h4>
        <p class="TutorialPostPageText">
        Разукрасьте кеды в соответствии с вашей кастом-задумкой. Хотя вам наверняка захочется сделать все очень быстро, медленное и последовательное нанесение краски позволит получить гораздо лучший результат. Если вы забыли, каким цветом нужно покрасить определенный участок, обратитесь к окончательному варианту вашего эскиза на бумаге.
        Используйте кисточки разной формы и размеров. Для тонких линий возьмите тонкую кисточку. Чтобы закрасить обширную область, используйте толстую кисточку или спонж.
        Чтобы создать узор в горошек, окунайте кончик ватной палочки прямо в краску и ставьте точки на обуви.</p>
    </div>

    <div class="TutorialPostPageImg">
        <img src="/fake_content/image_12.jpg" alt="кастом" />
    </div>

    <!--- --->

    <div class="TutorialPostPageContacts">
        <h6 class="TutorialPostPageContactsTitle">Контакты автора</h6>
        <p class="TutorialPostPageContactsDescription">Можете посмотреть больше моих работ по ссылкам: портфолио на бехансе и блог в телеге. Подписывайтесь, ставьте лайки и давайте кастомить вместе! :) А ещё мой мерч доступен для заказа</p>
        <div class="TutorialPostPageContactsAuthor">
            <div class="IdeaPostPageInfoUser">
                <div class="IdeaPostPageInfoUserAvatar"></div>
                    <div class="IdeaPostPageInfoUserNames">
                    <p class="IdeaPostPageInfoUserName UN"><%= post.user.email.split("@")[0] %></p>
                    <p class="IdeaPostPageInfoUserName NN">@<%= post.user.email.split("@")[0] %></p>
                </div>
            </div>
            <div class="TutorialPostPageAuthorLinks">
                <a class="AuthorLink VK" href="https://vk.com/lchok" target="_blank"></a>
                <a class="AuthorLink TG" href="https://t.me/loochok_media" target="_blank"></a>
            </div>
        </div>
    </div>

</div>

app/views/admin/tutorial_posts/index.html.erb
<div class="TutorialPostsPage">

  <div class="Banner TutorialPosts">
    <h1 class="BannerTitle TP">Туториалы</h1>
    <div class="BannerZigZag TutorialPosts"></div>
  </div>

  <div class="TagBlock">
    <div class="TagSections">
        <div class="TagSection Items">
          <p class="TagSectionTitle">Предметы</p>
          <div class="IconArrowDown Items"></div>
        </div>

        <div class="TagSection Tech">
          <p class="TagSectionTitle">Техники</p>
          <div class="IconArrowDown Tech"></div>
        </div>

        <div class="TagSection Mat">
          <p class="TagSectionTitle">Материалы</p>
          <div class="IconArrowDown Mat"></div>
        </div>
    </div>

    <div class="TagLists">
      <div class="TagList Items">
            <%= link_to tagged_admin_tutorial_posts_path("одежда"), class:"TagListTag" do %>
              одежда
            <% end %>
            <%= link_to tagged_admin_tutorial_posts_path("обувь"), class:"TagListTag" do %>
              обувь
            <% end %>
            <%= link_to tagged_admin_tutorial_posts_path("аксессуары"), class:"TagListTag" do %>
              аксессуары
            <% end %>
      </div>

      <div class="TagList Tech">
        <%= link_to tagged_admin_tutorial_posts_path("роспись"), class:"TagListTag" do %>
          роспись
        <% end %>
        <%= link_to tagged_admin_tutorial_posts_path("шитьё"), class:"TagListTag" do %>
          шитьё
        <% end %>
        <%= link_to tagged_admin_tutorial_posts_path("апсайклинг"), class:"TagListTag" do %>
          апсайклинг
        <% end %>
        <%= link_to tagged_admin_tutorial_posts_path("вязание"), class:"TagListTag" do %>
          вязание
        <% end %>
      </div>

      <div class="TagList Mat">
        <%= link_to tagged_admin_tutorial_posts_path("краски"), class:"TagListTag" do %>
          краски
        <% end %>
        <%= link_to tagged_admin_tutorial_posts_path("кожа"), class:"TagListTag" do %>
          кожа
        <% end %>
        <%= link_to tagged_admin_tutorial_posts_path("бисер"), class:"TagListTag" do %>
          бисер
        <% end %>
      </div>
    </div>
    <!--- <%#= link_to admin_tutorial_posts_path do %>
      <p class="TagSectionReset">Сбросить всё</p>
    <%# end %> --->
  </div>
  
  <%#= render @posts %>

  <div class="TutorialPostsCards">
    <% @posts.each do |post| %>
      <%= link_to admin_tutorial_post_path(post), class: "TutorialPostCard" do %>
        <%= render post %>
      <% end %>
    <% end %>
  </div>

</div>

app/views/admin/tutorial_posts/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="TutorialPostPage">

  <%= link_to :admin_tutorial_posts, class:"PostPageButton Back Fixed" do %>
    <div class="PostPageButtonIcon Back"></div>
    Назад
  <% end %>

  <% if can? :manage, @post %>
    <%= link_to edit_admin_tutorial_post_path(@post) do %>
        <div class="PostPageButton Edit Fixed">
            <div class="PostPageButtonIcon Edit"></div>
            Редактировать
        </div>
    <% end %>
    <%#= button_to "Удалить пост", admin_post_path(@post), method: :delete %>
  <% end %>

  <div class="TutorialPostPage Gride">

    <%#= render @post %>

    <%= render partial: "admin/tutorial_posts/tutorial_post_page", locals: {post: @post} %>

    <div class="TutorialPostPageComments">
      <p class="TutorialPostPageCommentTitle">Комментарии</p>
      <div class="TutorialPostPageCommentBlock">
        <div id="comments">
          <% @post.comments.each do |comment| %>
            <div class="TutorialPagePostComment">
              <%= render comment, post: @post %>
            </div>
          <% end %>
        </div>
      </div>
    </div>

  </div>

  <div class="IdeaPostPageSeeAlso">
    <div class="IdeaPostPageSeeAlsoTitle">Смотрите также:</div>
    <div class="IdeaPostPageSeeAlsoCards">
        <%= link_to admin_tutorial_post_path(22), class: "TutorialPostCard PP-1" do %>
            <%= render @recom_post1 %>
        <% end %>
        <%= link_to admin_tutorial_post_path(24), class: "TutorialPostCard PP-2" do %>
            <%= render @recom_post2 %>
        <% end %>
        <%= link_to admin_tutorial_post_path(23), class: "TutorialPostCard PP-3" do %>
            <%= render @recom_post3 %>
        <% end %>
    </div>
  </div>
  
</div>