config/routes.rb
Rails.application.routes.draw do
  post 'support/request_support'

  resources :posts do
    collection do
      get "by_tag/:tag", to: "posts#by_tag", as: "tagged"
    end
  end

  resources :idea_posts do
    collection do
      get "by_tag/:tag", to: "idea_posts#by_tag", as: "tagged"
    end
  end

  resources :tutorial_posts do
    collection do
      get "by_tag/:tag", to: "tutorial_posts#by_tag", as: "tagged"
    end
  end
  
  resources :comments, only: [:create]

  namespace :api do
    namespace :v1 do
      resources :comments
      resources :posts

      devise_scope :user do
        post "sign_up", to: "registrations#create"
        post "sign_in", to: "sessions#create"
        post "sign_out", to: "sessions#destroy"
      end
    end
  end


  namespace :admin do
    resources :idea_posts do
      collection do
        get "by_tag/:tag", to: "idea_posts#by_tag", as: "tagged"
      end
    end

    resources :tutorial_posts do
      collection do
        get "by_tag/:tag", to: "tutorial_posts#by_tag", as: "tagged"
      end
    end

    resources :posts do
      
      resources :comments

      collection do
        get "by_tag/:tag", to: "posts#by_tag", as: "tagged"
      end
      
    end

    resources :comments
    resources :subscriptions

    root to: "admin/posts#index"
  end

  resources :subscriptions, only: [:create, :show]

  devise_for :users


  get 'welcome/index'
  get 'welcome/about'
  get 'welcome/support'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "welcome#index"
end

app/models/post.rb
class Post < ApplicationRecord
    extend FriendlyId
    friendly_id :title, use: :slugged

    validates :title, presence: true
    validates :type, presence: true
    # validates :category, presence: true
    validates :post_image, presence: true

    has_many :comments, dependent: :destroy
    belongs_to :category
    belongs_to :user
    mount_uploader :post_image, PostImageUploader

    acts_as_taggable_on :tags

    # def api_as_json
    #     {
    #         title: title,
    #         description: description,
    #         category_name: category.name,
    #         post_image: post_image
    #     }
    # end

    # def to_param
    #     "#{title.parameterize}"
    # end

end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  load_and_authorize_resource
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all

    # Meta
    @title = "LÒÒCHOK | Все публикации"
    # end
  end

  def by_tag
    @posts = Post.tagged_with(params[:tag])
    render :index

    # Meta
    @title = "LÒÒCHOK | #{params[:tag]}"
    # end
  end

  # GET /posts/1 or /posts/1.json
  def show
    # Meta
    @title = "LÒÒCHOK | #{@post.title}"
    # end
  end

  # GET /posts/new
  def new
    @post = Post.new

    # Meta
    @title = "LÒÒCHOK | Новая публикация"
    # end
  end

  # GET /posts/1/edit
  def edit
    # Meta
    @title = "LÒÒCHOK | Редактирование публикации #{@post.title}"
    # end
  end

  # POST /posts or /posts.json
  def create
    p = nil
    if params[:post]
      p = post_params
    elsif params[:idea_post]
      p = idea_post_params
    elsif params[:tutorial_post]
      p = tutorial_post_params
    end

    @post = Post.new(p)

    respond_to do |format|
      if @post.save
        format.html { redirect_to admin_post_url(@post), notice: "Пост успешно создан" }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    p = nil
    if params[:post]
      p = post_params
    elsif params[:idea_post]
      p = idea_post_params
    elsif params[:tutorial_post]
      p = tutorial_post_params
    end

    respond_to do |format|
      if @post.update(p)
        format.html { redirect_to admin_post_url(@post), notice: "Пост успешно изменён" }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to admin_posts_url, notice: "Пост успешно удалён" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :type, :description, :post_image, :contetn_link, :tag_list, :category_id, :created_at).merge(user_id: current_user.id)
    end

    def idea_post_params
      params.require(:idea_post).permit(:title, :type, :description, :post_image, :contetn_link, :tag_list, :category_id, :created_at).merge(user_id: current_user.id)
    end

    def tutorial_post_params
      params.require(:tutorial_post).permit(:title, :type, :description, :post_image, :contetn_link, :tag_list, :category_id, :created_at).merge(user_id: current_user.id)
    end
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < Api::V1::ApplicationController

  def index
    @posts = Post.all

    # render :index
    # render json: @posts

    # render json: @posts.map { |post| post.api_as_json }
  end

  def show
    # @post = Post.find(params[:id])
    @post = Post.friendly.find(params[:id]) 
    # - что с френдли айди на этом этапе?
  end

  def create
    @user = User.find_by_jti(decrypt_payload[0]['jti'])
    @post = @user.posts.new(sti_post_params)

    if @post.save
      render json: @post.as_json
    else
      render json: @post.errors, status: :unprocessable_entity
    end
  end

  # def update
  #   if @post.update(sti_post_params)
  #     format.json { render :show, status: :ok, location: @post }
  #   else
  #     format.json { render json: @post.errors, status: :unprocessable_entity }
  #   end
  # end

  # def destroy
  #   @post.destroy
  #   format.json { head :no_content }
  # end

  private
    def sti_post_params
        p = nil
        
      if params[:post]
        p = params.require(:post)
      elsif params[:idea_post]
        p = params.require(:idea_post)
      elsif params[:tutorial_post]
        p = params.require(:tutorial_post)
      end

      p.permit(:title, :type, :description, :post_image, :contetn_link, :tag_list, :category_id, :created_at)
    end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all

    # Meta
    @title = "LÒÒCHOK | Все публикации"
    # end
  end

  def by_tag
    @posts = Post.tagged_with(params[:tag])
    render :index
  end

  # GET /posts/1 or /posts/1.json
  def show
    # Meta
    @title = "LÒÒCHOK | #{@post.title}"
    # end
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(sti_post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to post_url(@post), notice: "Пост успешно создан" }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(sti_post_params)
        format.html { redirect_to post_url(@post), notice: "Пост успешно изменён" }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Пост успешно удалён" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    # def post_params
    #   params.require(:post).permit(:title, :type, :description, :post_image, :category_id, :created_at).merge(user_id: current_user.id)
    # end

    # def idea_post_params
    #   params.require(:idea_post).permit(:title, :type, :description, :post_image, :category_id, :created_at).merge(user_id: current_user.id)
    # end

    # def tutorial_post_params
    #   params.require(:tutorial_post).permit(:title, :type, :description, :post_image, :category_id, :created_at).merge(user_id: current_user.id)
    # end

    def sti_post_params
        p = nil
        
      if params[:post]
        p = params.require(:post)
      elsif params[:idea_post]
        p = params.require(:idea_post)
      elsif params[:tutorial_post]
        p = params.require(:tutorial_post)
      end

      p.permit(:title, :type, :description, :post_image, :contetn_link, :tag_list, :category_id, :created_at).merge(user_id: current_user.id)
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<h2 style="font-size:32px; font-weight:900;"><%= post.class %></h2>

<%= form_with(model: post, url: url) do |form| %>
<%#= form_with(model: post, url: posts_path) do |form| %>
  <% if post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post.errors.count, "error") %>. Пост не может быть сохранён:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :"Заголовок", style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <br>

  <div>
    <%= form.label :"Текст публикации", style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :"Добавить ссылку", style: "display: block" %>
    <%= form.text_field :content_link %>
  </div>

  <br>

  <div>
    <%= form.label :"Загрузить изображение", style: "display: block" %>
    <%= form.file_field :post_image%>
  </div>

  <br>

  <div>
    <%= form.label :"Категория" %>
    <%= form.select :category_id, options_for_select(Category.all.map { |category| [category.name, category.id]})%>
  </div>

  <div>
    <%= form.label :"Тип" %>
    <%= form.select :type, ["IdeaPost", "TutorialPost"]%>
  </div>
  
  <br>

  <div>
    <%= form.submit :"Опубликовать"%>
  </div>
<% end %>

app/views/posts/_post.html.erb
<div id="<%= dom_id post %>">

  <p class="typeChips">
    <%= post.type %>
  </p>

  <p class="categoryChips">
    <%#= post.category.name %>
  </p>

  <p class="postDate">
    <%= post.created_at %>
  </p>

  <p>
    <%= post.user.email %>
  </p>

  <h2>
    <%= post.title%>
  </h2>

  <%= image_tag post.post_image.url, width: 300 if post.post_image.url %>

  <p>
    <%= post.description %>
  </p>

  <p>
    Комментариев: <%= post.comments.count %>
  </p>

</div>

app/views/posts/_postideapage.html.erb
<div class="postCard">

    <p class="typeChips idea">
        <%= post.type %>
    </p>

    <!--
    <p class="categoryChips">
        <%#= post.category.name %>
    </p>
    -->

    <div class="tagChipsRow">
        <% post.tag_list.each do |tag| %>
            <div class="tagChips">
                <%= tag %>
            </div>
        <% end %>
    </div>

    <p class="postDate">
        <%= post.created_at %>
    </p>

    <p>
        <%= post.user.email %>
    </p>

    <h2 style="font-size: 24px;">
        <%= post.title%>
    </h2>

    <%= image_tag post.post_image.url, width: 300 if post.post_image.url %>

    <p>
        <%= post.description %>
    </p>

    <p>
        Комментариев: <%= post.comments.count %>
    </p>

</div>

app/views/posts/_posttutorialpage.html.erb
<div class="postCard">

    <p class="typeChips tutorial">
        <%= post.type %>
    </p>

    <!--
    <p class="categoryChips">
        <%#= post.category.name %>
    </p>
    -->

    <div class="tagChipsRow">
        <% post.tag_list.each do |tag| %>
            <div class="tagChips">
                <%= tag %>
            </div>
        <% end %>
    </div>

    <p class="postDate">
        <%= post.created_at %>
    </p>

    <p>
        <%= post.user.email %>
    </p>

    <h2 style="color: blue;">
        <%= post.title%>
    </h2>

    <%= image_tag post.post_image.url, width: 300 if post.post_image.url %>

    <p>
        <%= post.description %>
    </p>

    <p>
        Комментариев: <%= post.comments.count %>
    </p>

</div>

app/views/posts/edit.html.erb
<div class="contentPage">

  <h1>Редактирование поста</h1>

  <%= render "form", post: @post, url: post_path(@post) %>

  <br>

  <div>
    <%= link_to "Показать пост", post_path(@post) %> |
    <%= link_to "Обратно ко всем постам", posts_path %>
  </div>

</div>

app/views/posts/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="contentPage">

  <h1>Посты</h1>

  <div class="tagChipsRow">
    <% Post.tag_counts_on(:tags).each do |tag| %>
      <%= link_to tagged_posts_path(tag.name) do %>
        <div class="tagChips">
          <%= tag.name %>
        </div>
      <% end %>
    <% end %>
  </div>

  <% if can? :create, Post %>
    <%= link_to "Новый пост", new_post_path %>
  <% end %>

  <div id="posts">
    <%#= render @posts %>
  </div>

  <div id="posts">
    <% @posts.each do |post| %>
      <%= link_to post_path(post) do %>
        <%= render post %>
      <% end %>
    <% end %>
  </div>

</div>

app/views/posts/new.html.erb
<div class="contentPage">

  <h1>Новый пост</h1>

  <%= render "form", post: @post, url: posts_path %>

  <%#= render "form", post: @post %>

  <br>

  <div>
    <%= link_to "Обратно ко всем постам", :back %>
  </div>
  
</div>

app/views/posts/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="contentPage">

  <% if @post.type == "IdeaPost" %>
    <%= render partial: "posts/postideapage", locals: {post: @post} %>
  <% elsif @post.type == "TutorialPost" %>
    <%= render partial: "posts/posttutorialpage", locals: {post: @post} %>
  <% end %>

  <%#= render @post %>

  <div>
    <%= link_to "Обратно ко всем постам", :back %> |

    <% if can? :manage, @post %>
      <%= link_to "Редактировать пост", edit_post_path(@post) %>
      <%= button_to "Удалить пост", post_path(@post), method: :delete %>
    <% end %>
  </div>

  <hr>

  <h3>Комментарии</h3>

  <%= render "comments/form", post: @post, comment: Comment.new %>

  <%#= link_to "Новый комментарий", new_post_comment_path(@post) %>
  <br>
  <br>
  <%#= render @post.comments, post: @post %>

  
  <div id="comments">
    <% @post.comments.each do |comment| %>
      <div class="commentCard"%>
        <%= render comment, post: @post %>
      </div>
    <% end %>
  </div>
  
</div>