config/routes.rb
Rails.application.routes.draw do
  post 'support/request_support'

  resources :posts do
    collection do
      get "by_tag/:tag", to: "posts#by_tag", as: "tagged"
    end
  end

  resources :idea_posts do
    collection do
      get "by_tag/:tag", to: "idea_posts#by_tag", as: "tagged"
    end
  end

  resources :tutorial_posts do
    collection do
      get "by_tag/:tag", to: "tutorial_posts#by_tag", as: "tagged"
    end
  end
  
  resources :comments, only: [:create]

  namespace :api do
    namespace :v1 do
      resources :comments
      resources :posts

      devise_scope :user do
        post "sign_up", to: "registrations#create"
        post "sign_in", to: "sessions#create"
        post "sign_out", to: "sessions#destroy"
      end
    end
  end


  namespace :admin do
    resources :idea_posts do
      collection do
        get "by_tag/:tag", to: "idea_posts#by_tag", as: "tagged"
      end
    end

    resources :tutorial_posts do
      collection do
        get "by_tag/:tag", to: "tutorial_posts#by_tag", as: "tagged"
      end
    end

    resources :posts do
      
      resources :comments

      collection do
        get "by_tag/:tag", to: "posts#by_tag", as: "tagged"
      end
      
    end

    resources :comments
    resources :subscriptions

    root to: "admin/posts#index"
  end

  resources :subscriptions, only: [:create, :show]

  devise_for :users


  get 'welcome/index'
  get 'welcome/about'
  get 'welcome/support'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "welcome#index"
end

app/models/idea_post.rb
class IdeaPost < Post
end

app/controllers/admin/idea_posts_controller.rb
class Admin::IdeaPostsController < Admin::ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.where("type = 'IdeaPost'")

    # Meta
    @title = "LÒÒCHOK | Идеи кастома"
    # end
  end

  def by_tag
    @posts = IdeaPost.tagged_with(params[:tag])
    render :index

    # Meta
    @title = "LÒÒCHOK | Фильтры"
    # end
  end

  # GET /posts/1 or /posts/1.json
  def show
    @recom_post1 = Post.find_by(id: "13")
    @recom_post2 = Post.find_by(id: "16")
    @recom_post3 = Post.find_by(id: "11")
  end

  # GET /posts/new
  def new
    @post = IdeaPost.new

    # Meta
    @title = "LÒÒCHOK | Новая идея"
    # end
  end

  # GET /posts/1/edit
  def edit
    # Meta
    @title = "LÒÒCHOK | Редактирование идеи"
    # end
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(idea_post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to admin_idea_post_url(@post), notice: "Пост успешно создан" }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(idea_post_params)
        format.html { redirect_to admin_idea_post_url(@post), notice: "Пост успешно изменён" }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to admin_idea_posts_url, notice: "Пост успешно удалён" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def idea_post_params
      params.require(:idea_post).permit(:title, :type, :description, :post_image, :tag_list, :category_id).merge(user_id: current_user.id)
    end
end

app/controllers/idea_posts_controller.rb
class IdeaPostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.where("type = 'IdeaPost'")
  end

  def by_tag
    @posts = IdeaPost.tagged_with(params[:tag])
    render :index
  end

  # GET /posts/1 or /posts/1.json
  def show
    @recom_post1 = Post.find_by(id: "13")
    @recom_post2 = Post.find_by(id: "16")
    @recom_post3 = Post.find_by(id: "11")
  end

  # GET /posts/new
  def new
    @post = IdeaPost.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(idea_post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to idea_post_url(@post), notice: "Пост успешно создан" }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(idea_post_params)
        format.html { redirect_to idea_post_url(@post), notice: "Пост успешно изменён" }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy

    respond_to do |format|
      format.html { redirect_to idea_posts_url, notice: "Пост успешно удалён" }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def idea_post_params
      params.require(:idea_post).permit(:title, :type, :description, :post_image, :tag_list, :category_id).merge(user_id: current_user.id)
    end
end

app/views/admin/idea_posts/_form.html.erb
<%= form_with(model: [:admin, idea_post]) do |form| %>
  <% if idea_post.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(idea_post.errors.count, "error") %>. Пост не может быть сохранён:</h2>

      <ul>
        <% idea_post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="IdeaFormPage Gride">

  <div class="LeftContent">
    <div class="BlockContent Img">
      <%= form.label :"Загрузить изображение", class:"TitleNewContent Img" %>
      <%= form.file_field :post_image, class:"FieldImg" %>
    </div>

    <!--- <div class="WrapperFakeImg">
      <div class="FieldImg Fake"></div>
      <div class="FieldImg Fake"></div>
      <div class="FieldImg Fake"></div>
    </div> --->
  </div>

  <div class="RightContent">
  <div class="TopContent">

    <div class="BlockContent Title">
      <%= form.label :"Название проекта", class:"TitleNewContent" %>
      <%= form.text_field :title, placeholder:"Кастом", class:"FieldContent Title" %>
    </div>

    <div class="BlockContent Tags">
      <%= form.label :"Тэги", class:"TitleNewContent" %>
      <%= form.text_field :tag_list, value: idea_post.tag_list.join(", "), class:"FieldContent Tags"  %>
    </div>
    </div>

    <div class="BottomContent">
    <div class="BlockContent Description">
      <%= form.label :"Описание проекта", class:"TitleNewContent" %>
      <%= form.text_area :description, placeholder:"Расскажите про ваш кастом", class:"FieldContent Description" %>
    </div>

    <!--- <div>
      <%#= form.label :"Добавить ссылку", style: "display: block" %>
      <%#= form.text_field :content_link %>
    </div> --->

    <div>
      <%= form.label :"Категория" %>
      <%= form.select :category_id, options_for_select(Category.all.map { |category| [category.name, category.id]})%>
    </div>

    <div>
      <%= form.label :"Тип" %>
      <%= form.select :type, [["Пост-идея", "IdeaPost"], ["Туториал", "TutorialPost"]] %>
      <%#= form.select :type, ["IdeaPost", "TutorialPost"]%>
    </div>

    <div class="FormButtons">
    <%= form.submit :"Опубликовать", class:"FormButton Post" %>

    <div class="FormButton Back">
      <%= link_to "Отменить", :back %>
    </div>
    </div>
  </div>
  </div>
  </div>
<% end %>

app/views/admin/idea_posts/_idea_post.html.erb
<div class="IdeaPostCardContent">

  <div class="IdeaPostCardImg">
    <%= image_tag idea_post.post_image.url if idea_post.post_image.url %>
  </div>

  <div class="IdeaPostCardInfo">
    <div class="IdeaPostCardInfoTop">
      <div class="IdeaCardInfoUser">
        <div class="IdeaCardInfoUserAvatar"></div>
        <div class="IdeaCardInfoUserNames">
          <p class="IdeaCardInfoUserName UN"><%= idea_post.user.email.split("@")[0] %></p>
          <p class="IdeaCardInfoUserName NN">@<%= idea_post.user.email.split("@")[0] %></p>
        </div>
      </div>
      <div class="IdeaPostCardLike"></div>
    </div>

    <div class="IdeaPostCardInfoBottom">
      <% idea_post.tag_list.each do |tag| %>
          <div class="PostCardTagChip">
              <%= tag %>
          </div>
      <% end %>
    </div>
  </div>

</div>

app/views/admin/idea_posts/_idea_post_page.erb
<div class="IdeaPostPage Gride">

    <div class="IdeaPostPageImg">
        <%= image_tag post.post_image.url if post.post_image.url %>
    </div>

    <div class="IdeaPostPageInfo">

        <div class="IdeaPostPageInfoTop">
            <div class="PostPageAbout Idea">
                <div class="PostPageTagsRow">
                    <% post.tag_list.each do |tag| %>
                        <%= link_to tagged_admin_idea_posts_path(tag), class:"PostPageTagChip" do %>
                            <%= tag %>
                        <% end %>
                    <% end %>
                </div>
                
                <p class="PostPageDate">
                    <%#= post.created_at %>
                    сегодня в&nbsp;10:05
                </p>

                <div class="IdeaPostPageInfoUser">
                    <div class="IdeaPostPageInfoUserAvatar"></div>
                        <div class="IdeaPostPageInfoUserNames">
                        <p class="IdeaPostPageInfoUserName UN"><%= post.user.email.split("@")[0] %></p>
                        <p class="IdeaPostPageInfoUserName NN">@<%= post.user.email.split("@")[0] %></p>
                    </div>
                </div>
            </div>

            <div class="IdeaPostPageTitleDescription">
                <h3 class="IdeaPostPageTitle"><%= post.title%></h3>
                <p class="IdeaPostPageDescription"><%= post.description %></p>
            </div>
        </div>

        <div class="IdeaPostPageInfoBottom">
            <p class="IdeaPostPageCommentTitle">Комментарии</p>
            <div class="IdeaPostPageCommentBlock">
                <div id="comments">
                    <% @post.comments.each do |comment| %>
                        <div class="IdeaPagePostComment">
                            <%= render comment, post: @post %>
                        </div>
                    <% end %>
                </div>
            </div>
        </div>

    </div>

</div>

<div class="IdeaPostPageSeeAlso">
    <div class="IdeaPostPageSeeAlsoTitle">Смотрите также:</div>
    <div class="IdeaPostPageSeeAlsoCards">
        <%= link_to admin_idea_post_path(13), class: "IdeaPostCard PP-1" do %>
            <%= render @recom_post1 %>
        <% end %>
        <%= link_to admin_idea_post_path(16), class: "IdeaPostCard PP-2" do %>
            <%= render @recom_post2 %>
        <% end %>
        <%= link_to admin_idea_post_path(11), class: "IdeaPostCard PP-3" do %>
            <%= render @recom_post3 %>
        <% end %>
    </div>
</div>

app/views/admin/idea_posts/index.html.erb
<div class="IdeaPostsPage">

  <div class="Banner IdeaPosts">
    <h1 class="BannerTitle IP-1">Идеи</h1>
    <h1 class="BannerTitle IP-2">кастома</h1>
    <div class="BannerZigZag IdeaPosts"></div>
  </div>

  <div class="TagBlock">
    <div class="TagSections">
        <div class="TagSection Items">
          <p class="TagSectionTitle">Предметы</p>
          <div class="IconArrowDown Items"></div>
        </div>

        <div class="TagSection Tech">
          <p class="TagSectionTitle">Техники</p>
          <div class="IconArrowDown Tech"></div>
        </div>

        <div class="TagSection Mat">
          <p class="TagSectionTitle">Материалы</p>
          <div class="IconArrowDown Mat"></div>
        </div>
    </div>

    <div class="TagLists">
      <div class="TagList Items">
            <%= link_to tagged_admin_idea_posts_path("одежда"), class:"TagListTag" do %>
              одежда
            <% end %>
            <%= link_to tagged_admin_idea_posts_path("обувь"), class:"TagListTag" do %>
              обувь
            <% end %>
            <%= link_to tagged_admin_idea_posts_path("аксессуары"), class:"TagListTag" do %>
              аксессуары
            <% end %>
      </div>

      <div class="TagList Tech">
        <%= link_to tagged_admin_idea_posts_path("роспись"), class:"TagListTag" do %>
          роспись
        <% end %>
        <%= link_to tagged_admin_idea_posts_path("шитьё"), class:"TagListTag" do %>
          шитьё
        <% end %>
        <%= link_to tagged_admin_idea_posts_path("апсайклинг"), class:"TagListTag" do %>
          апсайклинг
        <% end %>
        <%= link_to tagged_admin_idea_posts_path("вязание"), class:"TagListTag" do %>
          вязание
        <% end %>
      </div>

      <div class="TagList Mat">
        <%= link_to tagged_admin_idea_posts_path("краски"), class:"TagListTag" do %>
          краски
        <% end %>
        <%= link_to tagged_admin_idea_posts_path("кожа"), class:"TagListTag" do %>
          кожа
        <% end %>
        <%= link_to tagged_admin_idea_posts_path("бисер"), class:"TagListTag" do %>
          бисер
        <% end %>
      </div>
    </div>
    <!--- <%#= link_to admin_idea_posts_path do %>
      <p class="TagSectionReset">Сбросить всё</p>
    <%# end %> --->
  </div>
  
  <div class="IdeaPostsCards">
    <% @posts.each do |post| %>
      <%#= idea_post_url(post.title.parameterize) %>
      <%= link_to idea_post_path(post), class: "IdeaPostCard" do %>
        <%= render post %>
      <% end %>
    <% end %>
  </div>

</div>

app/views/admin/idea_posts/show.html.erb
<p style="color: green"><%= notice %></p>

<div class="IdeaPostPage">

  <%= link_to :admin_idea_posts do %>
    <div class="PostPageButton Desk Back Fixed">
      <div class="PostPageButtonIcon Back"></div>
      Назад
    </div>
    <div class="PostPageButton Mob Back Fixed">
      <div class="PostPageButtonIcon Back"></div>
    </div>
  <% end %>

  <% if can? :manage, @post %>
    <%= link_to edit_admin_idea_post_path(@post) do %>
        <div class="PostPageButton Desk Edit">
            <div class="PostPageButtonIcon Edit"></div>
            Редактировать
        </div>
        <div class="PostPageButton Mob Edit">
            <div class="PostPageButtonIcon Edit"></div>
        </div>
    <% end %>
    <%#= button_to "Удалить пост", admin_post_path(@post), method: :delete %>
  <% end %>

  <%#= render @post %>

  <%= render partial: "admin/idea_posts/idea_post_page", locals: {post: @post} %>
  
</div>